<div class="client">
    <div class="slider-client">
        <div id="sliderclient" class="owl-carousel owl-theme">
            <div class="item">
                <img src="<?= $block->getViewFileUrl('images/client-1_03.jpg') ?>" alt="" />
                <div class="name">Maria parker - model</div>
                <div class="badge-title">
                        <div>+</div>
                </div>
            </div>
            <div class="item">
                <img src="<?= $block->getViewFileUrl('images/client-2_03.jpg') ?>" alt="" />
                <div class="name">Maria parker - model</div>
                <div class="badge-title">
                        <div>+</div>
                </div>
            </div>
            <div class="item">
                <img src="<?= $block->getViewFileUrl('images/client-3_03.jpg') ?>" alt="" />
                <div class="name">Maria parker - model</div>
                <div class="badge-title">
                        <div>+</div>
                </div>
            </div>
            <div class="item">
                <img src="<?= $block->getViewFileUrl('images/client-4_03.jpg') ?>" alt="" />
                <div class="name">Maria parker - model</div>
                <div class="badge-title">
                        <div>+</div>
                </div>
            </div>
            <div class="item">
                <img src="<?= $block->getViewFileUrl('images/client-2_03.jpg') ?>" alt="" />
                <div class="name">Maria parker - model</div>
                <div class="badge-title">
                        <div>+</div>
                </div>
            </div>
            <div class="item">
                <img src="<?= $block->getViewFileUrl('images/client-1_03.jpg') ?>" alt="" />
                <div class="name">Maria parker - model</div>
                <div class="badge-title">
                        <div>+</div>
                </div>
            </div>
            <div class="item">
                <img src="<?= $block->getViewFileUrl('images/client-3_03.jpg') ?>" alt="" />
                <div class="name">Maria parker - model</div>
                <div class="badge-title">
                        <div>+</div>
                </div>
            </div>
            <div class="item">
                <img src="<?= $block->getViewFileUrl('images/client-4_03.jpg') ?>" alt="" />
                <div class="name">Maria parker - model</div>
                <div class="badge-title">
                        <div>+</div>
                </div>
            </div>
            <div class="item">
                <img src="<?= $block->getViewFileUrl('images/client-1_03.jpg') ?>" alt="" />
                <div class="name">Maria parker - model</div>
                <div class="badge-title">
                        <div>+</div>
                </div>
            </div>
            <div class="item">
                <img src="<?= $block->getViewFileUrl('images/client-2_03.jpg') ?>" alt="" />
                <div class="name">Maria parker - model</div>
                <div class="badge-title">
                        <div>+</div>
                </div>
            </div>
            <div class="item">
                <img src="<?= $block->getViewFileUrl('images/client-3_03.jpg') ?>" alt="" />
                <div class="name">Maria parker - model</div>
                <div class="badge-title">
                        <div>+</div>
                </div>
            </div>
            <div class="item">
                <img src="<?= $block->getViewFileUrl('images/client-4_03.jpg') ?>" alt="" />
                <div class="name">Maria parker - model</div>
                <div class="badge-title">
                        <div>+</div>
                </div>
            </div>
        </div>
    </div>
    <div class="explore">
        <span class="name"></span>
    </div>
    <img src="<?= $block->getViewFileUrl('images/client-banner_03.jpg') ?>" alt="" />
    <div class="title">
        <span class="title-name">Trusted by</span>
        <div class="name">
            <span>Celebrity<br></span>
            Clients
        </div>
    </div>

</div>
<script type="text/x-magento-init">
    {
    "*": {
        "sliderclient": {}
    }
}
</script>