<?php
/** @var \Magento\CatalogWidget\Block\Product\ProductsList $blockProductList */
$blockProductList = $block->getLayout()->createBlock('Magento\CatalogWidget\Block\Product\ProductsList');
$type = 'widget-product-grid';
$mode = 'grid'; 
$image = 'new_products_content_widget_grid';
$i = 0;
/** @var \Magento\Catalog\Model\ResourceModel\Product\Collection $items */
$products = $block->getProductCollection();
$brandNameCms = trim($block->getBrandName());
$linkBrand = $block->LinkStore(strtolower($brandNameCms));
$count = 0;
?>
<?php
foreach ($products as $product) {
	$brandName = trim($product->getResource()->getAttribute('brands')->getFrontend()->getValue($product));
	if (strcmp($brandNameCms, $brandName) == 0) {
		$count++;
	}
} 
?>
<?php if ($count > 0): ?>
	<div class="top-seller">
		<div class="title">
			<h2 class="title-white"><?= $brandNameCms.' Top Sellers' ?></h2>
			<a class="action primary" href="<?= $linkBrand ?>"><?= __("Browse All"); ?></a>
		</div>
		<div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">
			<div class="block-content">
				<div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
					<ol class="product-items <?= /* @noEscape */ $type ?>">
						<?php foreach ($products as $product): ?>
							<?php $i++; ?>
							<?php $brandName = trim($product->getResource()->getAttribute('brands')->getFrontend()->getValue($product)); ?>
							<?php if (strcmp($brandNameCms, $brandName) == 0): ?>
								<li class="product-item">
									<div class="product-item-info">
										<a href="<?= $blockProductList->escapeUrl($blockProductList->getProductUrl($product)) ?>" class="product-item-photo">
											<?= $blockProductList->getImage($product, $image)->toHtml() ?>
										</a>
										<div class="product-item-details">
											<strong class="product-item-name">
												<a title="<?= $block->escapeHtml($product->getName()) ?>"
													href="<?= $block->escapeUrl($blockProductList->getProductUrl($product)) ?>"
													class="product-item-link">
													<?= $block->escapeHtml($product->getName()) ?>
												</a>
											</strong>
											<?= $blockProductList->getProductPriceHtml($product, $type) ?>
										</div>
									</div>
									<?php if ($i == 10) { break; } ?>
								</li>
							<?php endif; ?>
						<?php endforeach; ?>
					</ol>
				</div>
			</div>
		</div>
	</div>
<?php endif; ?>
