<div id="order_comment_429">
    <strong><?php echo __('Order Comment-429') ?></strong>
    <span class="price"><?= $block->getOrderComment() ?></span></div>
<script type="text/javascript">
    require(
        ['jquery'],
        function($) {
            // var element1 = $('#delivery-date').detach();
            // var element2 = $('#custom_text').detach();
            var element3 = $('#order_comment_429').detach();

            // $('.order-shipping-method').append(element1);
            // $('.order-shipping-method').append(element2);
            $('.order-shipping-method').append(element3);


        }
    );
</script>